openapi: "3.1.0"
info:
  title: Simple OpenAPI example
  version: 0.0.1
  description: A simple example for OpenAPI
servers:
  - url: http://localhost:8080
    description: Sample server for this API
paths:
  /persons/{personId}:
    get:
      operationId: personGet
      summary: Fetch one person by id
      description: Get the person data
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: number
            example: 4
      responses:
        '200':
          description: Person
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                    description: Name of person
                    example: "Paul"
                  lastname:
                    type: string
                    description: Last name of person
                    example: "Paulson"
                  age:
                    type: number
                    description: The current age of the person
                    example: 42